image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd ./backend && yarn install && cd ../frontend && yarn install && yarn global add @vue/cli
  - command: mkdir -p mongodb && mkdir -p mongodb/data && mkdir -p mongodb/log && mongod --dbpath mongodb/data --fork --logpath mongodb/log/mongod.log && echo MongoDB up and running unless you see an error msg above


vscode:
  extensions:
    - octref.vetur@0.31.3:QHyAEoimIBiRDoL6WtEoRg==
    - esbenp.prettier-vscode@5.8.0:cd2Jz796EPVnD5zeCyctPw==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==