image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd ./backend && yarn install --mutex network
  - init: cd ./frontend && yarn install --mutex network
  - command: mkdir -p data && mongod --dbpath data
